# Generated by Django 4.1.4 on 2023-03-08 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wine_map", "0002_wineadditionalinfo_rename_tastes_taste_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wine",
            old_name="taste",
            new_name="tastes",
        ),
    ]
