# Generated by Django 4.1.4 on 2023-03-12 14:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wine_map", "0003_rename_taste_wine_tastes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wine",
            name="year",
        ),
        migrations.AlterField(
            model_name="wine",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="wine_map.country",
            ),
        ),
        migrations.RemoveField(
            model_name="wine",
            name="pairs_with",
        ),
        migrations.AlterField(
            model_name="wine",
            name="percent_of_alcohol",
            field=models.FloatField(
                blank=True,
                default=0.0,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(100.0),
                ],
            ),
        ),
        migrations.RemoveField(
            model_name="wine",
            name="sweetness",
        ),
        migrations.RemoveField(
            model_name="wine",
            name="tastes",
        ),
        migrations.AlterField(
            model_name="wine",
            name="wine_type",
            field=models.CharField(
                blank=True,
                choices=[("red", "Червоне"), ("white", "Біле"), ("rose", "Рожеве")],
                max_length=5,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="DishCategory",
        ),
        migrations.DeleteModel(
            name="Sweetness",
        ),
        migrations.DeleteModel(
            name="Taste",
        ),
        migrations.AddField(
            model_name="wine",
            name="pairs_with",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="wine",
            name="sweetness",
            field=models.CharField(
                blank=True,
                choices=[
                    ("brut", "брют"),
                    ("semi-sweet", "напівсолодке"),
                    ("semi-dry", "напівсухе"),
                    ("sweet", "солодке"),
                    ("dry", "сухе"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="wine",
            name="tastes",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
