# Generated by Django 4.1.4 on 2023-03-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wine_map", "0004_remove_wine_year_alter_wine_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wine",
            name="image_url",
            field=models.URLField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
