# Generated by Django 4.1.4 on 2023-03-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wine_map", "0006_alter_country_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wine",
            name="region",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="wine",
            name="pairs_with",
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
        migrations.AlterField(
            model_name="wine",
            name="tastes",
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
        migrations.AlterField(
            model_name="wine",
            name="wine_type",
            field=models.CharField(
                blank=True,
                choices=[("red", "Червоне"), ("white", "Біле"), ("rose", "Рожеве")],
                max_length=7,
                null=True,
            ),
        ),
    ]
