# Generated by Django 4.1.4 on 2023-03-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "wine_map",
            "0007_wine_region_alter_wine_pairs_with_alter_wine_tastes_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="wine",
            name="sweetness",
            field=models.CharField(
                blank=True,
                choices=[
                    ("brut", "брют"),
                    ("semi-sweet", "напівсолодке"),
                    ("semi-dry", "напівсухе"),
                    ("sweet", "солодке"),
                    ("dry", "сухе"),
                ],
                max_length=127,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="wine",
            name="wine_type",
            field=models.CharField(
                blank=True,
                choices=[("red", "Червоне"), ("white", "Біле"), ("rose", "Рожеве")],
                max_length=127,
                null=True,
            ),
        ),
    ]
