# Generated by Django 4.1.4 on 2023-03-14 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wine_map", "0008_alter_wine_sweetness_alter_wine_wine_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wine",
            name="pairs_with",
            field=models.CharField(blank=True, max_length=1027, null=True),
        ),
        migrations.AlterField(
            model_name="wine",
            name="tastes",
            field=models.CharField(blank=True, max_length=1027, null=True),
        ),
    ]
