# Generated by Django 4.1.4 on 2023-03-25 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wine_map", "0010_alter_wine_sweetness_alter_wine_wine_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="wine",
            name="in_favourites_of",
            field=models.ManyToManyField(
                related_name="favourite_wines", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
