# Generated by Django 4.1.4 on 2023-03-26 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wine_map", "0011_wine_in_favourites_of_alter_comment_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wine",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brand",
                to="wine_map.brand",
            ),
        ),
    ]
