# Generated by Django 4.1.4 on 2023-04-02 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wine_map", "0012_alter_wine_brand"),
    ]

    operations = [
        migrations.CreateModel(
            name="WineOfTheDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="wine_map.wine"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Wine of the day",
            },
        ),
    ]
