# Generated by Django 4.1.4 on 2023-04-04 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wine_map", "0015_alter_quizquestion_first"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizanswer",
            name="for_question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="wine_map.quizquestion",
            ),
        ),
    ]
