# Generated by Django 4.1.4 on 2023-04-09 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wine_map", "0014_wineoftheday_date"),
        ("wine_map", "0016_alter_quizanswer_for_question"),
    ]

    operations = []
