repos:
  - repo: https://github.com/ambv/black
    rev: 22.10.0
    hooks:
      - id: black
        language_version: python3.10
        exclude: ^.*\b(migrations)\b.*$
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
    - id: flake8
      additional_dependencies:
        - flake8-annotations==2.9.1
        - flake8-quotes==3.3.1
        - flake8-variables-names==0.0.5
