# fly.toml file generated for lteam-wine-map-backend on 2023-04-10T21:50:07+02:00

app = "lteam-wine-map-backend"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "ams"
processes = []

[env]
  PORT = "8000"

[[services]]
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 20
    soft_limit = 12
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
