name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set Up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
      - name: Run flake8
        run: flake8
      - name: Run black
        run: black backend
      - name: Run tests
        timeout-minutes: 5
        run: |
          cd backend
          python manage.py test
    env:
      DEBUG: 0
      SECRET_KEY: TEST
      CONFIGURATION: testing
      USE_HTTPS: 0
      POSTGRES_DB: None
      POSTGRES_USER: None
      POSTGRES_PASSWORD: None
      POSTGRES_HOST: None
      POSTGRES_PORT: None
